#..travis.yml

language: node_js
node_js:
  - '12.22.1'

branches:
  only:
    - master
    - develop

jobs:
  include:
    - stage: build master
      if: branch = master
      before_script:
        - npm install -g firebase-tools
        - npm install -g @angular/cli
      script:
        - npm run ci
      after_success:
        - firebase use angular-checklist-c7b61
        - firebase deploy --token $FIREBASE_TOKEN
    - stage: build develop
      if: branch = develop
      before_script:
        - npm install -g firebase-tools
        - npm install -g @angular/cli
      script:
        - npm run ci
      after_success:
        - firebase use angular-checklist-dev
        - firebase deploy --token $FIREBASE_TOKEN_DEVELOP

notifications:
  email:
    on_failure: kwinten.pisman@gmail.com
    on_success: kwinten.pisman@gmail.com
